kind: Deployment
apiVersion: apps/v1
metadata:
  name: admin-panel
  labels:
    app: admin-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-panel
  template:
    metadata:
      labels:
        app: admin-panel
    spec:
      containers:
        - name: admin-panel
          image: theechoseenonee/admin-panel:4.0
          ports:
            - name: http-server
              containerPort: 8080
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: DB_PORT
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: DB_PASSWORD
            - name: JAEGER_HOST
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: JAEGER_HOST
            - name: JAEGER_PORT
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: JAEGER_PORT
            - name: MAX_ON_PAGE
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: MAX_ON_PAGE
            - name: TIME_OUT
              valueFrom:
                configMapKeyRef:
                  name: admin-panel-config
                  key: TIME_OUT