// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/matrix/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matrix"
                ],
                "parameters": [
                    {
                        "description": "Matrix create",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MatrixDifferenceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully created matrix",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/matrix/create_no_parent": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matrix"
                ],
                "parameters": [
                    {
                        "description": "Matrix create",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagger.MatrixBase"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully created matrix",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/matrix/get_difference": {
            "get": {
                "description": "Retrieves the differences between two matrices identified by their names.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matrix"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the first matrix",
                        "name": "from_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of the second matrix",
                        "name": "to_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Found matrices differences",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MatrixDifferenceResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input, missing matrix names",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/matrix/get_history": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matrix"
                ],
                "parameters": [
                    {
                        "description": "Get data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagger.GetHistoryMatrix"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Found matrices",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/swagger.ResponseHistoryMatrix"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/matrix/get_matrices_by_duration": {
            "get": {
                "description": "Retrieves matrices that fall within the specified time duration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matrix"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start time of the duration (RFC3339 format)",
                        "name": "time_from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End time of the duration (RFC3339 format)",
                        "name": "time_to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved matrices within the specified duration",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Matrix"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input, missing or incorrect parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/matrix/get_matrix": {
            "get": {
                "description": "Retrieves a specific page of the matrix identified by its name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matrix"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the matrix to retrieve",
                        "name": "matrix_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number of the matrix to retrieve",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Microcategory ID if you need",
                        "name": "microcategory_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Region ID if you need",
                        "name": "region_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved the specified page of the matrix",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/swagger.Matrix"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input, missing or incorrect parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/matrix/get_matrix_pages": {
            "get": {
                "description": "Retrieves a specific page of matrices based on the matrix name provided.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matrix"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "The name of the matrix for which to retrieve the page",
                        "name": "matrix_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved the total number of pages for the specified matrix",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "400": {
                        "description": "Invalid input, missing or incorrect matrix_name parameter",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error occurred while retrieving the matrix page",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/matrix/get_tendency": {
            "put": {
                "description": "Retrieves price difference in time span",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matrix"
                ],
                "parameters": [
                    {
                        "description": "Get data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetTendencyNode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Found prices in time span and one before it",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ResponseTendencyNode"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/storage/current": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "responses": {
                    "200": {
                        "description": "Successfully switched matrix",
                        "schema": {
                            "$ref": "#/definitions/models.PreparedStorageSend"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/storage/send": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "parameters": [
                    {
                        "description": "Storage create",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.StorageBase"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully created matrix",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/storage/switch": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "storage"
                ],
                "responses": {
                    "200": {
                        "description": "Successfully switched matrix",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.GetTendencyNode": {
            "type": "object",
            "properties": {
                "microcategory_id": {
                    "type": "integer"
                },
                "region_id": {
                    "type": "integer"
                },
                "time_end": {
                    "type": "string"
                },
                "time_start": {
                    "type": "string"
                }
            }
        },
        "models.Matrix": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MatrixNode"
                    }
                },
                "is_baseline": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parent_name": {
                    "$ref": "#/definitions/null.String"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.MatrixDifferenceRequest": {
            "type": "object",
            "properties": {
                "added": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MatrixNode"
                    }
                },
                "deleted": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MatrixNode"
                    }
                },
                "is_baseline": {
                    "type": "boolean"
                },
                "new_name": {
                    "type": "string"
                },
                "parent_name": {
                    "type": "string"
                },
                "updated": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MatrixNode"
                    }
                }
            }
        },
        "models.MatrixDifferenceResponse": {
            "type": "object",
            "properties": {
                "added": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MatrixNode"
                    }
                },
                "deleted": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MatrixNode"
                    }
                },
                "updated": {
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/models.MatrixNode"
                        }
                    }
                }
            }
        },
        "models.MatrixNode": {
            "type": "object",
            "properties": {
                "microcategory_id": {
                    "type": "integer"
                },
                "price": {
                    "type": "integer"
                },
                "region_id": {
                    "type": "integer"
                }
            }
        },
        "models.PreparedStorageSend": {
            "type": "object",
            "properties": {
                "baseline": {
                    "type": "string"
                },
                "discount": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "discount_hops": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    }
                },
                "micro_category_hops": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "region_hops": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "segment_discount": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "models.ResponseTendencyNode": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.StorageBase": {
            "type": "object",
            "properties": {
                "baseline": {
                    "type": "string"
                },
                "discount": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "null.String": {
            "type": "object",
            "properties": {
                "string": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if String is not NULL",
                    "type": "boolean"
                }
            }
        },
        "swagger.GetHistoryMatrix": {
            "type": "object",
            "properties": {
                "is_baseline": {
                    "type": "boolean"
                },
                "time_end": {
                    "type": "string"
                },
                "time_start": {
                    "type": "string"
                }
            }
        },
        "swagger.Matrix": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MatrixNode"
                    }
                },
                "is_baseline": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parent_name": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "swagger.MatrixBase": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MatrixNode"
                    }
                },
                "is_baseline": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parent_name": {
                    "type": "string"
                }
            }
        },
        "swagger.ResponseHistoryMatrix": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "parent_name": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
