definitions:
  models.MatrixNode:
    properties:
      microcategory_id:
        type: integer
      price:
        type: integer
      region_id:
        type: integer
    type: object
  swagger.GetHistoryMatrix:
    properties:
      is_baseline:
        type: boolean
      time_end:
        type: string
      time_start:
        type: string
    type: object
  swagger.MatrixBase:
    properties:
      data:
        items:
          $ref: '#/definitions/models.MatrixNode'
        type: array
      is_baseline:
        type: boolean
      name:
        type: string
      parent_name:
        type: string
    type: object
  swagger.ResponseHistoryMatrix:
    properties:
      name:
        type: string
      parent_name:
        type: string
      timestamp:
        type: string
    type: object
info:
  contact: {}
paths:
  /matrix/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Matrix create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/swagger.MatrixBase'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created matrix
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create matrix
      tags:
      - matrix
  /matrix/get_history:
    put:
      consumes:
      - application/json
      parameters:
      - description: Get data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/swagger.GetHistoryMatrix'
      produces:
      - application/json
      responses:
        "200":
          description: Found matrixes
          schema:
            items:
              $ref: '#/definitions/swagger.ResponseHistoryMatrix'
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get matrixes by time start, time end and matrix type (can be null)
      tags:
      - matrix
swagger: "2.0"
