definitions:
  models.Matrix:
    properties:
      data:
        items:
          $ref: '#/definitions/models.MatrixNode'
        type: array
      is_baseline:
        type: boolean
      name:
        type: string
      parent_name:
        $ref: '#/definitions/null.String'
      timestamp:
        type: string
    type: object
  models.MatrixDifference:
    properties:
      added:
        items:
          $ref: '#/definitions/models.MatrixNode'
        type: array
      deleted:
        items:
          $ref: '#/definitions/models.MatrixNode'
        type: array
      updated:
        items:
          items:
            $ref: '#/definitions/models.MatrixNode'
          type: array
        type: array
    type: object
  models.MatrixNode:
    properties:
      microcategory_id:
        type: integer
      price:
        type: integer
      region_id:
        type: integer
    type: object
  null.String:
    properties:
      string:
        type: string
      valid:
        description: Valid is true if String is not NULL
        type: boolean
    type: object
  swagger.GetHistoryMatrix:
    properties:
      is_baseline:
        type: boolean
      time_end:
        type: string
      time_start:
        type: string
    type: object
  swagger.MatrixBase:
    properties:
      data:
        items:
          $ref: '#/definitions/models.MatrixNode'
        type: array
      is_baseline:
        type: boolean
      name:
        type: string
      parent_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /matrix/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Matrix create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/swagger.MatrixBase'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created matrix
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - matrix
  /matrix/get_difference:
    get:
      consumes:
      - application/json
      description: Retrieves the differences between two matrices identified by their
        names.
      parameters:
      - description: Name of the first matrix
        in: query
        name: from_name
        required: true
        type: string
      - description: Name of the second matrix
        in: query
        name: to_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Found matrices differences
          schema:
            items:
              $ref: '#/definitions/models.MatrixDifference'
            type: array
        "400":
          description: Invalid input, missing matrix names
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - matrix
  /matrix/get_history:
    put:
      consumes:
      - application/json
      parameters:
      - description: Get data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/swagger.GetHistoryMatrix'
      produces:
      - application/json
      responses:
        "200":
          description: Found matrices
          schema:
            items:
              $ref: '#/definitions/models.Matrix'
            type: array
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - matrix
swagger: "2.0"
