definitions:
  models.InData:
    properties:
      micro_category_id:
        type: integer
      region_id:
        type: integer
    type: object
  models.OutData:
    properties:
      matrix_name:
        type: string
      micro_category_id:
        type: integer
      price:
        type: integer
      region_id:
        type: integer
    type: object
  models.UpdateMatrixName:
    properties:
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /price:
    put:
      consumes:
      - application/json
      parameters:
      - description: Get price
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.InData'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully responsed with price
          schema:
            $ref: '#/definitions/models.OutData'
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - price
  /recalculate:
    put:
      consumes:
      - application/json
      parameters:
      - description: Get price
        in: body
        name: name
        required: true
        schema:
          $ref: '#/definitions/models.UpdateMatrixName'
      produces:
      - application/json
      responses:
        "204":
          description: Successfully recalculated and updated price information
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - price
swagger: "2.0"
